trigger:
- main

pool:
  name: "My-pool"

stages:
- stage: MiseAJourInfrastructureAzure
  jobs:
  - job: MiseAJourJob
    displayName: "Mise à jour de l'infrastructure Azure"
    steps:
    - checkout: self

    - task: Maven@3
  displayName: 'Installer Maven'
  inputs:
    mavenVersionOption: 'Default'
    mavenPathOption: 'Default'


    - script: |
        # Vider la mémoire vive
        free -h && sudo sysctl vm.drop_caches=3 && free -h
        rm -rf terraform
        git clone https://github.com/Asma-Bmdn/pipline-azure.git
        cd terraform
        # Remplacer les clés
        sed -i '11s|default = ""|default = "GY3CVDN9R"|" terraform.tfvars  
        # terraform init and apply
        terraform init
        terraform apply --auto-approve
      displayName: "Mise à jour de l'infrastructure Azure"

