trigger:
- main

pool:
  name: My-pool

stages:
- stage: MiseAJourInfrastructureAzure
  jobs:
  - job: MiseAJourJob
    displayName: "Mise à jour de l'infrastructure Azure"
    steps:
    - checkout: self

    - script: |
        # Vider la mémoire vive
        free -h
        sudo sysctl vm.drop_caches=3
        free -h

        # Cloner le référentiel Terraform
        git clone https://github.com/Asma-Bmdn/pipline-azure.git
        cd pipline-azure

        # Remplacer les clés dans terraform.tfvars
        sudo sed -i "11s|default = \"\"|default = \"C3DGMZ4WQ\"|" terraform.tfvars

        # Terraform init et apply
        sudo terraform init
        sudo terraform apply --auto-approve
      displayName: "Mise à jour de l'infrastructure Azure"
   
- stage: InstallerMavenEtOpenJDK
  jobs:
  - job: BuildDockerImage
    displayName: 'Build Docker image with Maven and OpenJDK'
    container:
      image: ubuntu:latest  # Utiliser une image Ubuntu comme base
    steps:
    - checkout: self

    # Créer un Dockerfile pour construire l'image
    - script: |
        echo "FROM ubuntu:latest" > Dockerfile
        echo "RUN apt-get update && apt-get install -y openjdk-11-jdk maven" >> Dockerfile
      displayName: 'Create Dockerfile'

    # Construire l'image Docker
    - script: |
        sudo docker build -t maven-openjdk .
      displayName: 'Build Docker image'

    # Vérifier l'image Docker créée
    - script: |
        sudo docker images
      displayName: 'Check Docker images'

    # Exécuter un conteneur basé sur l'image avec Maven et OpenJDK installés
    - script: |
        sudo docker run -it --rm maven-openjdk mvn --version
        sudo docker run -it --rm maven-openjdk java -version
      displayName: 'Verify Maven and OpenJDK installation in Docker container'
