trigger:
- main

pool:
  name: My-pool1

jobs:
- job: BuildAndRunDockerContainer
  displayName: 'Build and Run Docker Container'
  steps:
  - checkout: self

  - script: |
      # Vérifier si OpenJDK est installé
      if command -v java &> /dev/null; then
          echo "OpenJDK already installed. Nothing to do."
      else
          # Installer OpenJDK
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          echo "OpenJDK installed successfully."
      fi

      # Vérifier si Maven est installé
      if command -v mvn &> /dev/null; then
          echo "Maven already installed. Nothing to do."
      else
          # Installer Maven
          sudo apt-get install -y maven
          echo "Maven installed successfully."
      fi

      # Afficher les versions installées
      java -version
      mvn --version
      
      # Vérifier si Docker est installé
      if command -v docker &> /dev/null; then
          echo "Docker already installed. Nothing to do."
      else
          # Installer Docker
          sudo apt-get install -y docker.io
          echo "Docker installed successfully."
          
          # Assurer que Docker est dans le chemin d'accès
          export PATH=$PATH:/usr/bin/docker
      fi

      # Afficher la version de Docker
      docker --version
    displayName: 'Install OpenJDK, Maven, and Docker'

  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: 'Dockerfile'
      tags: '/docker-repository:latest'

  - script: 'docker run -it docker-repository:latest'
    displayName: 'Run Docker Container'
