trigger:
- main

pool:
  name: My-pool

stages:
- stage: MiseAJourInfrastructureAzure
  jobs:
  - job: MiseAJourJob
    displayName: "Mise à jour de l'infrastructure Azure"
    steps:
    - checkout: self

    - script: |
        # Vider la mémoire vive
        free -h
        sudo sysctl vm.drop_caches=3
        free -h

        # Cloner le référentiel Terraform
        git clone https://github.com/Asma-Bmdn/pipline-azure.git
        cd pipline-azure

        # Remplacer les clés dans terraform.tfvars
        sed -i '11s|default = ""|default = "C3DGMZ4WQ"|' terraform.tfvars

        # Terraform init et apply
        terraform init
        terraform apply --auto-approve
      displayName: "Mise à jour de l'infrastructure Azure"
      
 stages:
- stage: InstallerMavenEtOpenJDK
  jobs:
  - job: InstallerMavenEtOpenJDKJob
    displayName: "Installer Maven et OpenJDK"
    steps:
    - checkout: self

    - script: |
        # Récupérer des informations sur l'agent
        AGENT_NAME=$(My-pool)
        AGENT_IP=$(My-pool -I | awk '{print $1}')

        # Installer OpenJDK
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk

        # Installer Maven
        sudo apt-get install -y maven

        # Afficher les versions installées
        java -version
        mvn --version

        # Afficher des informations sur la machine virtuelle
        echo "Machine virtuelle : $AGENT_NAME"
        echo "Adresse IP : $AGENT_IP"
      displayName: "Installer Maven et OpenJDK"


