trigger:
- main

pool: 
  name: My-pool

stages:
- stage: MiseAJourInfrastructureAzure
  jobs:
  - job: MiseAJourJob
    displayName: "Mise à jour de l'infrastructure Azure"
    steps:
    - checkout: self

    - script: |
        # Vider la mémoire vive
        free -h
        sudo sysctl vm.drop_caches=3
        free -h

        # Cloner le référentiel Terraform
        git clone https://github.com/Asma-Bmdn/pipline-azure.git
        cd pipline-azure

        # Remplacer les clés dans terraform.tfvars
        sed -i "11s|default = \"\"|default = \"C3DGMZ4WQ\"|" terraform.tfvars

        # Terraform init et apply
        terraform init
        terraform apply --auto-approve
      displayName: "Mise à jour de l'infrastructure Azure"

- stage: PreparerInfra
  jobs:
  - job: PreparerJob
    displayName: "Préparation de l'infrastructure"
    pool: 
      name: my-pool9
    steps:
    - checkout: self

    - script: |
        # Vérifier si Docker est déjà installé
        if ! command -v docker &> /dev/null
        then
            echo "Docker est déjà installé. Rien à faire."
        else
            # Installer Docker
            sudo apt-get update
            sudo apt-get install -y curl
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh

            # Ajouter l'utilisateur au groupe Docker
            sudo usermod -aG docker $USER

            # Déconnexion et reconnexion pour appliquer les changements
            exec sudo su - $USER
        fi
      displayName: "Installer Docker (si nécessaire)"

  
- stage: InstallerMavenEtOpenJDK
  jobs:
  - job: InstallerMavenEtOpenJDKJob
    displayName: "Installer Maven et OpenJDK"
    pool: 
      name: my-pool9
    steps:
    - checkout: self

    - script: |
        # Créer un conteneur Docker à partir de l'image openjdk:latest
        docker run --name maven-openjdk -d openjdk:latest tail -f /dev/null

        # Installer Maven à l'intérieur du conteneur
        docker exec maven-openjdk bash -c 'apt-get update && apt-get install -y maven'

        # Installer OpenJDK à l'intérieur du conteneur
        docker exec maven-openjdk bash -c 'apt-get update && apt-get install -y openjdk-11-jdk'

        # Afficher les versions installées
        docker exec maven-openjdk java -version
        docker exec maven-openjdk mvn --version

        # Supprimer le conteneur après utilisation
        docker rm -f maven-openjdk
      displayName: "Installer Maven et OpenJDK"
