trigger:
- main

pool:
  name: My-pool

stages:
- stage: MiseAJourInfrastructureAzure
  jobs:
  - job: MiseAJourJob
    displayName: "Mise à jour de l'infrastructure Azure"
    steps:
    - checkout: self

    - script: |
        # Vider la mémoire vive
        free -h
        sudo sysctl vm.drop_caches=3
        free -h

        # Cloner le référentiel Terraform
        git clone https://github.com/Asma-Bmdn/pipline-azure.git
        cd pipline-azure

        # Remplacer les clés dans terraform.tfvars
        sed -i "11s|default = \"\"|default = \"GY3CVDN9R\"|" terraform.tfvars

        # Terraform init et apply
        terraform init
        terraform apply --auto-approve
      displayName: "Mise à jour de l'infrastructure Azure"
