trigger:
- main

pool:
  name: My-pool

stages:
- stage: MiseAJourInfrastructureAzure
  jobs:
  - job: MiseAJourJob
    displayName: "Mise à jour de l'infrastructure Azure"
    steps:
    - checkout: self

    - script: |
        # Vider la mémoire vive
        free -h
        sudo sysctl vm.drop_caches=3
        free -h

        # Cloner le référentiel Terraform
        git clone https://github.com/Asma-Bmdn/pipline-azure.git
        cd pipline-azure

        # Remplacer les clés dans terraform.tfvars
        sed -i "11s|default = \"\"|default = \"C3DGMZ4WQ\"|" terraform.tfvars

        # Terraform init et apply
        terraform init
        terraform apply --auto-approve
      displayName: "Mise à jour de l'infrastructure Azure"
   
- stage: InstallerMavenEtOpenJDK
  jobs:
  - job: BuildDockerImage
    displayName: 'Build Docker image with Maven and OpenJDK'
    container:
      image: ubuntu:latest  # Utiliser une image Ubuntu comme base
    steps:
    - checkout: self

    # Installer Docker
    - script: |
        sudo apt-get update
        sudo apt-get install -y docker.io
      displayName: 'Install Docker'

    # Installer OpenJDK et Maven
    - script: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk maven
      displayName: 'Install OpenJDK and Maven'
