trigger:
- main

pool:
  name: 'My-pool'

stages:
- stage: MiseAJourInfrastructureAzure
  jobs:
  - job: MiseAJourJob
    displayName: 'Mise à jour de l'infrastructure Azure'
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: 'Installer Maven'
      inputs:
        version: '3.9'
        mavenVersionOption: 'Path'
        mavenPathOption: 'MavenWrapper'

    - script: |
        # Vider la mémoire vive
        free -h && sudo sysctl vm.drop_caches=3 && free -h
        rm -rf terraform
        git clone https://github.com/Asma-Bmdn/pipline-azure.git
        cd terraform
        # Remplacer les clés
        sed -i '11s|default = ""|default = "VOTRE_CLE_AZURE"|" terraform.tfvars  # Remplacez VOTRE_CLE_AZURE par votre clé Azure
        # terraform init and apply
        terraform init
        terraform apply --auto-approve
      displayName: 'Mise à jour de l'infrastructure Azure'
